NapaProjects.OnlineMarket/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Routing;
using System.Security.Cryptography.X509Certificates;

namespace NapaProjects.OnlineMarket.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private ICartRepository _cartRepository;
        private IProductRepository _productRepository;
        private readonly UserManager<AppUser> _userManager;

        public CartController(ICartRepository cartRepository, UserManager<AppUser> userManager, IProductRepository productRepository)
        {
            _cartRepository = cartRepository;
            _userManager = userManager;
            _productRepository = productRepository;
        }

        public async Task<IActionResult> CartView(string  userName, string returnUrl)
        {
            var user = await _userManager.FindByNameAsync(userName??User.Identity.Name);
            ViewBag.ReturnUrl = returnUrl;
            return View(new CartModel(_cartRepository.GetByUser(user.Id)
                , _cartRepository.Orders(_cartRepository.GetByUser(user.Id).Id)));
        }

        public IActionResult AddToCart(int productId, string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            ViewBag.ProductId = productId;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddToCart(int productId, string returnUrl, int quantity)
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            _cartRepository.AddToCart(new Order { ProductId = productId, Quantity = quantity }, user.Id);
            return RedirectToAction(nameof(CartView), new { userName = User.Identity.Name, returnUrl = returnUrl });
        }

        [HttpPost]
        public IActionResult DeleteOrder(int orderId, string returnUrl)
        {
            _cartRepository.DeleteFromCart(orderId);
            return Redirect(returnUrl);
        }
    }
}

NapaProjects.OnlineMarket/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.V4.Pages.Account.Internal;

namespace NapaProjects.OnlineMarket.Controllers
{
    public class LoginController : Controller
    {
        private UserManager<AppUser> userManager;

        private RoleManager<IdentityRole<int>> roleManager;

        private SignInManager<AppUser> signInManager;

        private UserValidator<AppUser> userValidator;

        private PasswordValidator<AppUser> passwordValidator;

        public LoginController(UserManager<AppUser> userManager,
                    RoleManager<IdentityRole<int>> roleManager, SignInManager<AppUser> signInManager,
                    UserValidator<AppUser> userValidator, PasswordValidator<AppUser> passwordValidator)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
            this.signInManager = signInManager;
            this.userValidator = userValidator;
            this.passwordValidator = passwordValidator;
        }

        [Authorize]
        [AllowAnonymous]
        public async Task<IActionResult> SignUp(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View(new UserModel());
        }

        [HttpPost]
        [Authorize]
        [AllowAnonymous]
        public async Task<IActionResult> SignUp(UserModel user, string password, string returnUrl)
        {
            AppUser newUser = new AppUser
            {
                UserName = user.UserName,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                PhoneNumber = user.PhoneNumber
            };
            var result = await passwordValidator.ValidateAsync(userManager, newUser, password);
            if (!result.Succeeded)
            {
                foreach (var er in result.Errors)
                {
                    ModelState.AddModelError(er.Code, er.Description);
                }
            }
            result = await userValidator.ValidateAsync(userManager, newUser);
            if (!result.Succeeded)
            {
                foreach (var er in result.Errors)
                {
                    ModelState.AddModelError(er.Code, er.Description);
                }
            }
            
            result = await userManager.CreateAsync(newUser,password);
            if (!result.Succeeded)
            {
                foreach (var er in result.Errors)
                {
                    ModelState.AddModelError(er.Code, er.Description);
                }
            }
            if (ModelState.IsValid)
            {
                await userManager.AddToRoleAsync(newUser, AppRoles.UserRole.Name);
                await signInManager.PasswordSignInAsync(newUser, password, false, false);
                return Redirect(returnUrl);
            }
                ViewBag.ReturnUrl = returnUrl;
                return View(user);
            
        }

        [Authorize]
        [AllowAnonymous]
        public IActionResult SignIn(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View(new SignInModel());
        }

        [HttpPost]
        [Authorize]
        [AllowAnonymous]
        public async Task<IActionResult> SignIn(SignInModel loginModel, string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            var user = await userManager.FindByNameAsync(loginModel.UserName);
            if(user == null)
            {
                ModelState.AddModelError("UserName", $"'{loginModel.UserName}' user name is not found");
                return View(new {userName = loginModel.UserName, password = loginModel.password});
            }
            await signInManager.SignOutAsync();
            var signInResult = await signInManager.PasswordSignInAsync(user, loginModel.password, false, false);
            if (signInResult.Succeeded)
            {

                return Redirect(returnUrl??"/");
            }
            ModelState.AddModelError("password", "This password is wrong");
            return View(loginModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> SignOut(string returnUrl)
        {
            await signInManager.SignOutAsync();
            Console.WriteLine("Directed to " + returnUrl);
            return Redirect(returnUrl);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult CreateUser(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View(new UserModel());
        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Users()
        {
            List<UserModel> Users = userManager.Users.ToList()
        .Select(x =>
        {
            var y = (UserModel)x;
            roleManager.Roles.ToList().ForEach(async role =>
            {
                if (await userManager.IsInRoleAsync(x, role.Name))
                {
                    y.Roles.Add(role.Name);
                }
            });
            return y;
        }).ToList();
            return View(Users);
        }
                                     
                                     //=> View(userManager.Users.Select(u => (UserModel)u).ToList());


        [Authorize(Roles ="Admin")]
        [HttpPost]
        public async Task<IActionResult> CreateUser(UserModel newUser, string password, string returnUrl)
        {
            AppUser user = new AppUser()
            {
                UserName = newUser.UserName,
                FirstName = newUser.FirstName,
                LastName = newUser.LastName,
                Email = newUser.Email,
                PhoneNumber = newUser.PhoneNumber
            };

            

            var userValidate = await userValidator.ValidateAsync(userManager, user);

            if (!userValidate.Succeeded)
            {
                userValidate.Errors.ToList().ForEach(er => ModelState.AddModelError(er.Code, er.Description));
            }

            var passwordValidate = await passwordValidator.ValidateAsync(userManager, user, password);

            if (!passwordValidate.Succeeded)
            {
                passwordValidate.Errors.ToList().ForEach(er => ModelState.AddModelError(er.Code, er.Description));
            }
            if (ModelState.IsValid)
            {
                var result = await userManager.CreateAsync(user, password);
                if (!result.Succeeded)
                {
                    return View(newUser);
                }
                await userManager.AddToRoleAsync(user, AppRoles.UserRole.Name);
                return Redirect(returnUrl);
            }
            return View(user);
        }

        [Authorize(Roles="Admin")]
        [HttpPost]
        public async Task<IActionResult> DeleteUser(string userName, string returnUrl)
        {
            var result = await userManager.DeleteAsync(await userManager.FindByNameAsync(userName));
            if (!result.Succeeded)
            {
                foreach (var er in result.Errors)
                {
                    ModelState.AddModelError(er.Code, er.Description);
                }
            }
            return Redirect(returnUrl);

        }
    }
}

NapaProjects.OnlineMarket/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NapaProjects.OnlineMarket</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NapaProjects.OnlineMarket.styles.css" asp-append-version="true" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"
            asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">OnlineMarket</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        @if(User.isAdmin()){
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Cart" asp-action="CartView"
                               asp-route-returnUrl="@Context.PathAndQuery()" asp-route-userName="@User.Identity.Name">Cart</a>
                            </li>
                            <li class="nav-item">
                                <form method="post"><button class="nav-link text-dark" asp-action="Signout" asp-controller="Login"
                                asp-route-returnUrl="@Context.PathAndQuery()">Sign Out</button></form>
                            </li>
                        }
                        else if(User.isUser()){
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Cart" asp-action="CartView"
                               asp-route-returnUrl="@Context.PathAndQuery()" asp-route-userName="@User.Identity.Name">Cart</a>
                            </li>
                            <li class="nav-item">
                                <form method="post">
                                    <button class="nav-link text-dark" asp-action="Signout" asp-controller="Login"
                                        asp-route-returnUrl="@Context.PathAndQuery()">
                                        Sign Out
                                    </button>
                                </form>
                            </li>
                        }
                        else{
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-action="SignIn" asp-controller="Login"
                                asp-route-returnUrl="@Context.PathAndQuery()">Sign In</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-action="SignUp" asp-controller="Login"
                               asp-route-returnUrl="@Context.PathAndQuery()">Sign Up</a>
                            </li>
                        }

                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
           
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>