NapaProjects.OnlineMarket/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Routing;
using System.Security.Cryptography.X509Certificates;

namespace NapaProjects.OnlineMarket.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private ICartRepository _cartRepository;
        private IProductRepository _productRepository;
        private readonly UserManager<AppUser> _userManager;

        public CartController(ICartRepository cartRepository, UserManager<AppUser> userManager, IProductRepository productRepository)
        {
            _cartRepository = cartRepository;
            _userManager = userManager;
            _productRepository = productRepository;
        }

        public async Task<IActionResult> CartView(string  userName, string returnUrl)
        {
            var user = await _userManager.FindByNameAsync(userName??User.Identity.Name);
            ViewBag.ReturnUrl = returnUrl;
            return View(new CartModel(_cartRepository.GetByUser(user.Id)
                , _cartRepository.Orders(_cartRepository.GetByUser(user.Id).Id)));
        }

        public IActionResult AddToCart(int productId, string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            ViewBag.ProductId = productId;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddToCart(int productId, string returnUrl, int quantity)
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            _cartRepository.AddToCart(new Order { ProductId = productId, Quantity = quantity }, user.Id);
            return RedirectToAction(nameof(CartView), new { userName = User.Identity.Name, returnUrl = returnUrl });
        }

        [HttpPost]
        public IActionResult DeleteOrder(int orderId, string returnUrl)
        {
            _cartRepository.DeleteFromCart(orderId);
            return Redirect(returnUrl);
        }
    }
}

NapaProjects.OnlineMarket/Controllers/HistoryController.cs
using Microsoft.AspNetCore.Mvc;

namespace NapaProjects.OnlineMarket.Controllers
{
    public class HistoryController : Controller
    {
        private readonly IHistoryRepository _historyRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IProductRepository _productRepository;

        public HistoryController(IHistoryRepository historyRepository, ICategoryRepository categoryRepository,
            IProductRepository productRepository)
        {
            _historyRepository = historyRepository;
            _categoryRepository = categoryRepository;
            _productRepository = productRepository;
        }

        public IActionResult Index()
        {
            return View(_historyRepository.ProductHistory.Select(x =>
            {
                var y = (HistoryModel)x;
                y.RelatedCategoryName = _categoryRepository.Get(x.RelatedCategoryId.Value).Name;
                return y;
            }));
        }

        public IActionResult HistoryWithid(int id, string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            ViewBag.ProductName = _productRepository.Get(id).Name;
            return View(_historyRepository.ProductHistory.Where(x => x.RelatedProductId == id).Select(x =>
            {
                var y = (HistoryModel)x;
                y.RelatedCategoryName = _categoryRepository.Get(x.RelatedCategoryId.Value).Name;
                return y;
            }));
        }
    }
}

NapaProjects.OnlineMarket/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace NapaProjects.OnlineMarket.Controllers;

public class ProductController : Controller
{
    private readonly IProductRepository _productRepository;
    private readonly ICategoryRepository _categoryRepository;

    public ProductController(IProductRepository productRepository, ICategoryRepository categoryRepository)
    {
        _productRepository = productRepository;
        _categoryRepository = categoryRepository;
    }

    public IActionResult ProductList() => View(_productRepository.Products.Select(x => (ProductModel)x));

    public IActionResult CreateProduct(string returnUrl)
    {
        ViewBag.ReturnUrl = returnUrl;
        ViewBag.SelectList = new SelectList(_categoryRepository.Categories
            .Select(x => new { Id = x.Id, Name = x.Name }),"Id","Name");
        return View(new ProductModel());
    }

    [HttpPost]
    public IActionResult CreateProduct(ProductModel newProduct, string returnUrl)
    {
        Product product = newProduct;
        if (newProduct.CategoryCheck)
        {
            var catId = _categoryRepository.Create(new Category
            {
                Name = newProduct.NewCategoryName,
                Description = newProduct.NewCategoryDescription
            });
            product.CategoryId = catId;
        }

        _productRepository.Create(product);

        return Redirect(returnUrl);
    }
    [Authorize(Roles="Admin")]
    [HttpPost]
    public IActionResult DeleteProduct(int id, string returnUrl)
    {
        var result = _productRepository.Delete(id);
        if (!result)
        {
            ModelState.AddModelError("id", $"Product with Id {id} Not Found!");
        }
        return Redirect(returnUrl);
    }

    [Authorize(Roles = "Admin")]
    public IActionResult UpdateProduct(int id, string returnUrl)
    {
        ViewBag.ReturnUrl = returnUrl;
        ViewBag.SelectList = new SelectList(_categoryRepository.Categories
            .Select(x => new { Id = x.Id, Name = x.Name }), "Id", "Name");
        var product = _productRepository.Get(id);
        if(product is null)
        {
            ModelState.AddModelError(nameof(id), "Product with Id {id} Not Found!");
            return Redirect(returnUrl);
        }
        return View((ProductModel)product);
    }

    [Authorize(Roles = "Admin")]
    [HttpPost]
    public IActionResult UpdateProduct(ProductModel product, string returnUrl)
    {
        if (product.CategoryCheck)
        {
            Console.WriteLine("\n\n\n********************************");
            Console.WriteLine("                  " + product.CategoryCheck);
            Console.WriteLine("*****************\n******************\n\n\n\n\n");
            if (string.IsNullOrEmpty(product.NewCategoryName)
                || string.IsNullOrWhiteSpace(product.NewCategoryName))
                ModelState.AddModelError(nameof(product.NewCategoryName),$"Name is required to new category");
            if (string.IsNullOrEmpty(product.NewCategoryDescription)
                || string.IsNullOrWhiteSpace(product.NewCategoryDescription))
                ModelState.AddModelError(nameof(product.NewCategoryDescription),
                            $"Description is required to new category");

        }
        else
        {
            if (product.CategoryId == 0)
                ModelState.AddModelError(nameof(product.CategoryId), "Category is not chosen");
        }

        if (!ModelState.IsValid)
        {
            ViewBag.ReturnUrl = returnUrl;
            ViewBag.SelectList = new SelectList(_categoryRepository.Categories
                .Select(x => new { Id = x.Id, Name = x.Name }), "Id", "Name");
            
            return View((ProductModel)product);
        }

        Product updatedProduct = product;

        if (product.CategoryCheck)
        {
            var id = _categoryRepository.Create(new Category
            {
                Name = product.NewCategoryName,
                Description = product.NewCategoryDescription
            });
            updatedProduct.CategoryId = id;
        }
        
        _productRepository.Update(updatedProduct);
        return Redirect(returnUrl);
    }


}

NapaProjects.OnlineMarket/Views/Product/CreateProduct.cshtml
@model ProductModel


<div class="p-2 bg-primary" style="color: white;">
    <h3>
        Add Product 
    </h3>
</div>

<form method="post" asp-action="CreateProduct">
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control"/>
    </div>
    <div class="form-group">
        <label asp-for="Price">Price</label>
        <input asp-for="Price" class="form-control" />
    </div>
    
    <div class="form-group " id="selectCategory">
        <label asp-for="CategoryId">Category</label>
        <select asp-for="CategoryId" class="form-control" asp-items="@ViewBag.SelectList">

        </select>
    </div>
    
    <div class="form-group row collapse" id="newCategory">
        <div class="col-5">
            <label asp-for="NewCategoryName">new category name</label>
            <input type="text" asp-for="NewCategoryName" class="form-control" />
        </div>
        <div class="col-5">
            <label asp-for="NewCategoryDescription">new category description</label>
            <input type="text" asp-for="NewCategoryDescription" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <select asp-for="CategoryCheck" id="categoryCheck">
            <option value="false">Use exist category</option>
            <option value="true">Create a new category</option>
        </select>
        <label for="categoryCheck">Create a new Category</label>
    </div>
    <input type="hidden" name="returnUrl" value="@ViewBag.ReturnUrl" />
    <div class="form-group m-1">
        <button type="submit" class="btn btn-primary">
            Create
        </button>
        <a href="@ViewBag.ReturnUrl" class="btn btn-outline-danger">Cancel</a>
    </div>
</form>

<script>
    $( "#categoryCheck" ).change(function(){
        if($(this).val() === "true"){
            $( "#selectCategory" ).addClass("collapse");
            $( "#newCategory" ).removeClass( "collapse" );
        }
        else{
            $( "#newCategory" ).addClass( "collapse" );
            $( "#selectCategory" ).removeClass( "collapse" );
        }
    });

    console.log("scriipt loaded");
</script>

NapaProjects.OnlineMarket/Views/Product/ProductList.cshtml
@model IEnumerable<ProductModel>

<div class="p-2 bg-primary" style="color: white;">
    <h3>
        Product List
    </h3>
</div>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Name</th><th>Category</th><th>Price</th>@if (User.isAdmin()) { <th></th>} <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var product in Model)
        {
            <tr>
                <td>@product.Name</td><td>@product.CategoryName</td><td>@product.Price</td>
                @if (User.isAdmin())
                {
                    <td>
                        <a asp-action="HistoryWithId" asp-controller="History" asp-route-id="@product.Id"
                        asp-route-returnUrl="@Context.PathAndQuery()">History details</a>
                    </td>
                }
                <td>
                    @if (User.isUser() || User.isUser())
                    {
                        <form method="post" >
                            <input type="hidden" name="returnUrl" value="@Context.PathAndQuery()"/>
                            <input type="hidden" name="id" value="@product.Id"/>
                            <button type="submit" asp-action="DeleteProduct" class="btn btn-outline-danger">
                                Delete
                            </button>
                            @if (User.isAdmin())
                            {
                                <a class="btn btn-outline-primary" asp-action="UpdateProduct"
                       asp-route-id="@product.Id" asp-route-returnUrl="@Context.PathAndQuery()">
                                    Update
                                </a>
                            <a class="btn btn-success" asp-action="AddToCart" asp-controller="Cart"
                            asp-route-returnUrl="@Context.PathAndQuery()" asp-route-productId="@product.Id">
                                Add to cart
                            </a>
                            
                            }
                        </form>

                    }else {
                        <p>To order product you must signin</p>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="p-1" style="align-items: center;">
    <a class="btn btn-primary col-5" asp-action="CreateProduct" asp-route-returnUrl="@Context.PathAndQuery()">
        Create a new product
    </a>
</div>

NapaProjects.OnlineMarket/Views/Product/UpdateProduct.cshtml
@model ProductModel


<div class="p-2 bg-primary" style="color: white;">
    <h3>
        Update Product 
    </h3>
</div>

<div asp-validation-summary="All" class="text-danger"></div>

<form method="post" asp-action="UpdateProduct">
    <input asp-for="Id" type="hidden" />
    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Price">Price</label>
        <input asp-for="Price" class="form-control" />
    </div>

    <div class="form-group " id="selectCategory">
        <label asp-for="CategoryId">Category</label>
        <select asp-for="CategoryId" class="form-control" asp-items="@ViewBag.SelectList">
        </select>
    </div>

    <div class="form-group row collapse" id="newCategory">
        <div class="col-5">
            <label asp-for="NewCategoryName">new category name</label>
            <input type="text" asp-for="NewCategoryName" class="form-control" />
        </div>
        <div class="col-5">
            <label asp-for="NewCategoryDescription">new category description</label>
            <input type="text" asp-for="NewCategoryDescription" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <select asp-for="CategoryCheck" id="categoryCheck">
            <option value="false" selected="@(!Model.CategoryCheck)">Use exsist category</option>
            <option value="true" selected="@Model.CategoryCheck">Create a new category</option>
        </select>
    </div>
    <input type="hidden" name="returnUrl" value="@ViewBag.ReturnUrl" />
    <div class="form-group m-1">
        <button type="submit" class="btn btn-primary">
            Save
        </button>
        <a href="@ViewBag.ReturnUrl" class="btn btn-outline-danger">Cancel</a>
    </div>
</form>
     


<script asp-append-version="true">

    console.log( "scriipt loaded" );
    

    $( "#categoryCheck" ).change( function () {
        console.log( typeof $( "#categoryCheck" ).val() );
        if ( $( "#categoryCheck" ).val() === "true" ) {
            console.log(true)
            $( "#selectCategory" ).addClass( "collapse" );
            $( "#newCategory" ).removeClass( "collapse" );
        }
        else {
            console.log(false);
            $( "#newCategory" ).addClass( "collapse" );
            $( "#selectCategory" ).removeClass( "collapse" );
        }
    } );
</script>